### ISSUE TITLE
Add dev jokes

### ISSUE THREAD

**Issue by swapnadeepmohapatra** [swapnadeepmohapatra/add-dev-jokes#1]
Find dev jokes and that to readme.md

**Comment by georgioupanayiotis** [comment]
@swapnadeepmohapatra i have created another PR as well check it out [here](https://github.com/swapnadeepmohapatra/add-dev-jokes/pull/5)

**Comment by swapnadeepmohapatra** [comment]
Add jokes to jokes.json
